{{- if and .Values.providerConfig.create .Values.providerConfig.credentials.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.providerConfig.credentials.existingSecret }}
  namespace: {{ include "azureTomcat.namespace" . }}
  labels:
    {{- include "azureTomcat.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.providerConfig.credentials.key }}: {{ include "azureTomcat.credentialsJson" . | quote }}
{{- end }}
