apiVersion: imagebuilder.io/v1alpha1
kind: PlatformProvider
metadata:
  name: aws
  namespace: imagebuilder-system
  labels:
    app.kubernetes.io/name: imagebuilder-aws-ubuntu24
    app.kubernetes.io/part-of: imagebuilder
spec:
  package: ghcr.io/anwendt/imagebuilder-provider-aws@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  packagePullPolicy: IfNotPresent
  security:
    allowedRegistries:
      - ghcr.io/anwendt
    requireDigest: true
    verifySignature: true
