// api/provider/v1/provider.proto
//
// This is the stable gRPC contract between the core operator and external
// platform provider pods. Treat field numbers as permanent — never reuse them.
//
// Breaking changes require a new package: imagebuilder.provider.v2
//
// License: Apache 2.0
//
// Generate Go code:
//   protoc --proto_path=api/provider/v1 \
//          --go_out=api/provider/v1 --go_opt=paths=source_relative \
//          --go-grpc_out=api/provider/v1 --go-grpc_opt=paths=source_relative \
//          api/provider/v1/provider.proto
//
// Or: make proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: provider.proto

package providerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlatformProvider_GetCapabilities_FullMethodName      = "/imagebuilder.provider.v1.PlatformProvider/GetCapabilities"
	PlatformProvider_ValidateConfig_FullMethodName       = "/imagebuilder.provider.v1.PlatformProvider/ValidateConfig"
	PlatformProvider_UploadArtifact_FullMethodName       = "/imagebuilder.provider.v1.PlatformProvider/UploadArtifact"
	PlatformProvider_RegisterImage_FullMethodName        = "/imagebuilder.provider.v1.PlatformProvider/RegisterImage"
	PlatformProvider_DeleteArtifact_FullMethodName       = "/imagebuilder.provider.v1.PlatformProvider/DeleteArtifact"
	PlatformProvider_HealthCheck_FullMethodName          = "/imagebuilder.provider.v1.PlatformProvider/HealthCheck"
	PlatformProvider_ReconcileRemoteBuild_FullMethodName = "/imagebuilder.provider.v1.PlatformProvider/ReconcileRemoteBuild"
	PlatformProvider_CleanupRemoteBuild_FullMethodName   = "/imagebuilder.provider.v1.PlatformProvider/CleanupRemoteBuild"
)

// PlatformProviderClient is the client API for PlatformProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PlatformProvider is the gRPC service that every external provider pod must implement.
// The operator connects to the provider via a Unix socket at /var/run/provider/plugin.sock
// inside the provider pod (shared via emptyDir volume between operator sidecar and provider).
type PlatformProviderClient interface {
	// GetCapabilities is called once after the provider pod becomes ready.
	// The operator uses the response to populate PlatformProvider.status.capabilities
	// and to validate VMImage targets before starting a build.
	GetCapabilities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CapabilitiesResponse, error)
	// ValidateConfig checks a ProviderConfig before a build starts.
	// Called every time a VMImage references a ProviderConfig backed by this provider.
	ValidateConfig(ctx context.Context, in *ValidateConfigRequest, opts ...grpc.CallOption) (*ValidateConfigResponse, error)
	// UploadArtifact streams the build artifact from the operator to the provider.
	// The provider uploads it to the target platform (S3, Glance, datastore, ...).
	// Streaming allows large images (50GB+) without memory pressure.
	UploadArtifact(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UploadChunk, UploadProgress], error)
	// RegisterImage makes the uploaded artifact available as a platform image.
	// Called after UploadArtifact completes successfully.
	RegisterImage(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*ImageRef, error)
	// DeleteArtifact removes a previously uploaded artifact.
	// Called on build failure or explicit cleanup. Must be idempotent.
	DeleteArtifact(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	// HealthCheck is called periodically by the operator.
	// Return an error to signal the provider is unhealthy.
	HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error)
	// ReconcileRemoteBuild starts or continues a provider-owned remote build.
	// This is additive in v1 and must be idempotent for the same build_id and
	// operation_ref. Providers that do not advertise build_modes=["remote"] may
	// return Unimplemented.
	ReconcileRemoteBuild(ctx context.Context, in *RemoteBuildRequest, opts ...grpc.CallOption) (*RemoteBuildResponse, error)
	// CleanupRemoteBuild removes provider-owned resources for a remote build.
	// Called after deletion, timeout, cancellation, or failed reconciliation.
	// Must be idempotent and must not return or log secret material.
	CleanupRemoteBuild(ctx context.Context, in *RemoteBuildRequest, opts ...grpc.CallOption) (*RemoteBuildCleanupResponse, error)
}

type platformProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewPlatformProviderClient(cc grpc.ClientConnInterface) PlatformProviderClient {
	return &platformProviderClient{cc}
}

func (c *platformProviderClient) GetCapabilities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapabilitiesResponse)
	err := c.cc.Invoke(ctx, PlatformProvider_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformProviderClient) ValidateConfig(ctx context.Context, in *ValidateConfigRequest, opts ...grpc.CallOption) (*ValidateConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateConfigResponse)
	err := c.cc.Invoke(ctx, PlatformProvider_ValidateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformProviderClient) UploadArtifact(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UploadChunk, UploadProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PlatformProvider_ServiceDesc.Streams[0], PlatformProvider_UploadArtifact_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadChunk, UploadProgress]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PlatformProvider_UploadArtifactClient = grpc.BidiStreamingClient[UploadChunk, UploadProgress]

func (c *platformProviderClient) RegisterImage(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*ImageRef, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImageRef)
	err := c.cc.Invoke(ctx, PlatformProvider_RegisterImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformProviderClient) DeleteArtifact(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, PlatformProvider_DeleteArtifact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformProviderClient) HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, PlatformProvider_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformProviderClient) ReconcileRemoteBuild(ctx context.Context, in *RemoteBuildRequest, opts ...grpc.CallOption) (*RemoteBuildResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoteBuildResponse)
	err := c.cc.Invoke(ctx, PlatformProvider_ReconcileRemoteBuild_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformProviderClient) CleanupRemoteBuild(ctx context.Context, in *RemoteBuildRequest, opts ...grpc.CallOption) (*RemoteBuildCleanupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoteBuildCleanupResponse)
	err := c.cc.Invoke(ctx, PlatformProvider_CleanupRemoteBuild_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlatformProviderServer is the server API for PlatformProvider service.
// All implementations must embed UnimplementedPlatformProviderServer
// for forward compatibility.
//
// PlatformProvider is the gRPC service that every external provider pod must implement.
// The operator connects to the provider via a Unix socket at /var/run/provider/plugin.sock
// inside the provider pod (shared via emptyDir volume between operator sidecar and provider).
type PlatformProviderServer interface {
	// GetCapabilities is called once after the provider pod becomes ready.
	// The operator uses the response to populate PlatformProvider.status.capabilities
	// and to validate VMImage targets before starting a build.
	GetCapabilities(context.Context, *Empty) (*CapabilitiesResponse, error)
	// ValidateConfig checks a ProviderConfig before a build starts.
	// Called every time a VMImage references a ProviderConfig backed by this provider.
	ValidateConfig(context.Context, *ValidateConfigRequest) (*ValidateConfigResponse, error)
	// UploadArtifact streams the build artifact from the operator to the provider.
	// The provider uploads it to the target platform (S3, Glance, datastore, ...).
	// Streaming allows large images (50GB+) without memory pressure.
	UploadArtifact(grpc.BidiStreamingServer[UploadChunk, UploadProgress]) error
	// RegisterImage makes the uploaded artifact available as a platform image.
	// Called after UploadArtifact completes successfully.
	RegisterImage(context.Context, *RegisterRequest) (*ImageRef, error)
	// DeleteArtifact removes a previously uploaded artifact.
	// Called on build failure or explicit cleanup. Must be idempotent.
	DeleteArtifact(context.Context, *DeleteRequest) (*DeleteResponse, error)
	// HealthCheck is called periodically by the operator.
	// Return an error to signal the provider is unhealthy.
	HealthCheck(context.Context, *Empty) (*HealthResponse, error)
	// ReconcileRemoteBuild starts or continues a provider-owned remote build.
	// This is additive in v1 and must be idempotent for the same build_id and
	// operation_ref. Providers that do not advertise build_modes=["remote"] may
	// return Unimplemented.
	ReconcileRemoteBuild(context.Context, *RemoteBuildRequest) (*RemoteBuildResponse, error)
	// CleanupRemoteBuild removes provider-owned resources for a remote build.
	// Called after deletion, timeout, cancellation, or failed reconciliation.
	// Must be idempotent and must not return or log secret material.
	CleanupRemoteBuild(context.Context, *RemoteBuildRequest) (*RemoteBuildCleanupResponse, error)
	mustEmbedUnimplementedPlatformProviderServer()
}

// UnimplementedPlatformProviderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlatformProviderServer struct{}

func (UnimplementedPlatformProviderServer) GetCapabilities(context.Context, *Empty) (*CapabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedPlatformProviderServer) ValidateConfig(context.Context, *ValidateConfigRequest) (*ValidateConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateConfig not implemented")
}
func (UnimplementedPlatformProviderServer) UploadArtifact(grpc.BidiStreamingServer[UploadChunk, UploadProgress]) error {
	return status.Error(codes.Unimplemented, "method UploadArtifact not implemented")
}
func (UnimplementedPlatformProviderServer) RegisterImage(context.Context, *RegisterRequest) (*ImageRef, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterImage not implemented")
}
func (UnimplementedPlatformProviderServer) DeleteArtifact(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteArtifact not implemented")
}
func (UnimplementedPlatformProviderServer) HealthCheck(context.Context, *Empty) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedPlatformProviderServer) ReconcileRemoteBuild(context.Context, *RemoteBuildRequest) (*RemoteBuildResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReconcileRemoteBuild not implemented")
}
func (UnimplementedPlatformProviderServer) CleanupRemoteBuild(context.Context, *RemoteBuildRequest) (*RemoteBuildCleanupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CleanupRemoteBuild not implemented")
}
func (UnimplementedPlatformProviderServer) mustEmbedUnimplementedPlatformProviderServer() {}
func (UnimplementedPlatformProviderServer) testEmbeddedByValue()                          {}

// UnsafePlatformProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlatformProviderServer will
// result in compilation errors.
type UnsafePlatformProviderServer interface {
	mustEmbedUnimplementedPlatformProviderServer()
}

func RegisterPlatformProviderServer(s grpc.ServiceRegistrar, srv PlatformProviderServer) {
	// If the following call panics, it indicates UnimplementedPlatformProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlatformProvider_ServiceDesc, srv)
}

func _PlatformProvider_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformProviderServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformProvider_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformProviderServer).GetCapabilities(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformProvider_ValidateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformProviderServer).ValidateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformProvider_ValidateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformProviderServer).ValidateConfig(ctx, req.(*ValidateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformProvider_UploadArtifact_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PlatformProviderServer).UploadArtifact(&grpc.GenericServerStream[UploadChunk, UploadProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PlatformProvider_UploadArtifactServer = grpc.BidiStreamingServer[UploadChunk, UploadProgress]

func _PlatformProvider_RegisterImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformProviderServer).RegisterImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformProvider_RegisterImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformProviderServer).RegisterImage(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformProvider_DeleteArtifact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformProviderServer).DeleteArtifact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformProvider_DeleteArtifact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformProviderServer).DeleteArtifact(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformProvider_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformProviderServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformProvider_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformProviderServer).HealthCheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformProvider_ReconcileRemoteBuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoteBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformProviderServer).ReconcileRemoteBuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformProvider_ReconcileRemoteBuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformProviderServer).ReconcileRemoteBuild(ctx, req.(*RemoteBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformProvider_CleanupRemoteBuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoteBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformProviderServer).CleanupRemoteBuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformProvider_CleanupRemoteBuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformProviderServer).CleanupRemoteBuild(ctx, req.(*RemoteBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlatformProvider_ServiceDesc is the grpc.ServiceDesc for PlatformProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlatformProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "imagebuilder.provider.v1.PlatformProvider",
	HandlerType: (*PlatformProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCapabilities",
			Handler:    _PlatformProvider_GetCapabilities_Handler,
		},
		{
			MethodName: "ValidateConfig",
			Handler:    _PlatformProvider_ValidateConfig_Handler,
		},
		{
			MethodName: "RegisterImage",
			Handler:    _PlatformProvider_RegisterImage_Handler,
		},
		{
			MethodName: "DeleteArtifact",
			Handler:    _PlatformProvider_DeleteArtifact_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _PlatformProvider_HealthCheck_Handler,
		},
		{
			MethodName: "ReconcileRemoteBuild",
			Handler:    _PlatformProvider_ReconcileRemoteBuild_Handler,
		},
		{
			MethodName: "CleanupRemoteBuild",
			Handler:    _PlatformProvider_CleanupRemoteBuild_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadArtifact",
			Handler:       _PlatformProvider_UploadArtifact_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "provider.proto",
}
