// api/provider/v1/provider.proto
//
// This is the stable gRPC contract between the core operator and external
// platform provider pods. Treat field numbers as permanent — never reuse them.
//
// Breaking changes require a new package: imagebuilder.provider.v2
//
// License: Apache 2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: provider.proto

package providerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{0}
}

type CapabilitiesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// provider_name must match the PlatformProvider CR name e.g. "aws"
	ProviderName    string `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	ProviderVersion string `protobuf:"bytes,2,opt,name=provider_version,json=providerVersion,proto3" json:"provider_version,omitempty"` // semver e.g. "v1.2.0"
	// formats this provider can receive e.g. ["vmdk", "ova"]
	Formats []string `protobuf:"bytes,3,rep,name=formats,proto3" json:"formats,omitempty"`
	// os_families this provider supports: "linux", "windows"
	OsFamilies []string `protobuf:"bytes,4,rep,name=os_families,json=osFamilies,proto3" json:"os_families,omitempty"`
	// protocol_version of this proto schema e.g. "v1"
	// Operator rejects providers with incompatible protocol versions.
	ProtocolVersion string `protobuf:"bytes,5,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CapabilitiesResponse) Reset() {
	*x = CapabilitiesResponse{}
	mi := &file_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesResponse) ProtoMessage() {}

func (x *CapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*CapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{1}
}

func (x *CapabilitiesResponse) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *CapabilitiesResponse) GetProviderVersion() string {
	if x != nil {
		return x.ProviderVersion
	}
	return ""
}

func (x *CapabilitiesResponse) GetFormats() []string {
	if x != nil {
		return x.Formats
	}
	return nil
}

func (x *CapabilitiesResponse) GetOsFamilies() []string {
	if x != nil {
		return x.OsFamilies
	}
	return nil
}

func (x *CapabilitiesResponse) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

type ValidateConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// provider_config_name is the name of the ProviderConfig CR
	ProviderConfigName string `protobuf:"bytes,1,opt,name=provider_config_name,json=providerConfigName,proto3" json:"provider_config_name,omitempty"`
	// credentials is the decoded secret content
	Credentials map[string][]byte `protobuf:"bytes,2,rep,name=credentials,proto3" json:"credentials,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// region / endpoint from ProviderConfigSpec
	Region   string `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	Endpoint string `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Insecure bool   `protobuf:"varint,5,opt,name=insecure,proto3" json:"insecure,omitempty"`
	// extra holds provider-specific key-value config
	Extra         map[string]string `protobuf:"bytes,6,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateConfigRequest) Reset() {
	*x = ValidateConfigRequest{}
	mi := &file_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateConfigRequest) ProtoMessage() {}

func (x *ValidateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateConfigRequest.ProtoReflect.Descriptor instead.
func (*ValidateConfigRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateConfigRequest) GetProviderConfigName() string {
	if x != nil {
		return x.ProviderConfigName
	}
	return ""
}

func (x *ValidateConfigRequest) GetCredentials() map[string][]byte {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *ValidateConfigRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ValidateConfigRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *ValidateConfigRequest) GetInsecure() bool {
	if x != nil {
		return x.Insecure
	}
	return false
}

func (x *ValidateConfigRequest) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

type ValidateConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // human-readable error when valid=false
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateConfigResponse) Reset() {
	*x = ValidateConfigResponse{}
	mi := &file_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateConfigResponse) ProtoMessage() {}

func (x *ValidateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateConfigResponse.ProtoReflect.Descriptor instead.
func (*ValidateConfigResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateConfigResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UploadChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// data is the raw bytes of this chunk
	Data   []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Offset int64  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Last   bool   `protobuf:"varint,3,opt,name=last,proto3" json:"last,omitempty"` // true on the final chunk
	// These fields are only populated in the FIRST chunk (offset=0)
	Format         string            `protobuf:"bytes,10,opt,name=format,proto3" json:"format,omitempty"`     // ImageFormat e.g. "vmdk"
	Checksum       string            `protobuf:"bytes,11,opt,name=checksum,proto3" json:"checksum,omitempty"` // sha256:hex of the complete artifact
	TotalSizeBytes int64             `protobuf:"varint,12,opt,name=total_size_bytes,json=totalSizeBytes,proto3" json:"total_size_bytes,omitempty"`
	OsFamily       string            `protobuf:"bytes,13,opt,name=os_family,json=osFamily,proto3" json:"os_family,omitempty"`
	Metadata       map[string]string `protobuf:"bytes,14,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// provider_config_name identifies which ProviderConfig to use
	ProviderConfigName string `protobuf:"bytes,15,opt,name=provider_config_name,json=providerConfigName,proto3" json:"provider_config_name,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UploadChunk) Reset() {
	*x = UploadChunk{}
	mi := &file_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadChunk) ProtoMessage() {}

func (x *UploadChunk) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadChunk.ProtoReflect.Descriptor instead.
func (*UploadChunk) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{4}
}

func (x *UploadChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *UploadChunk) GetLast() bool {
	if x != nil {
		return x.Last
	}
	return false
}

func (x *UploadChunk) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *UploadChunk) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *UploadChunk) GetTotalSizeBytes() int64 {
	if x != nil {
		return x.TotalSizeBytes
	}
	return 0
}

func (x *UploadChunk) GetOsFamily() string {
	if x != nil {
		return x.OsFamily
	}
	return ""
}

func (x *UploadChunk) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UploadChunk) GetProviderConfigName() string {
	if x != nil {
		return x.ProviderConfigName
	}
	return ""
}

type UploadProgress struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	BytesWritten int64                  `protobuf:"varint,1,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	TotalBytes   int64                  `protobuf:"varint,2,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	Phase        string                 `protobuf:"bytes,3,opt,name=phase,proto3" json:"phase,omitempty"` // "uploading" | "converting" | "verifying"
	Message      string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// provider_ref is set in the final progress message (phase="done")
	// It is passed back to RegisterImage.
	ProviderRef   string `protobuf:"bytes,5,opt,name=provider_ref,json=providerRef,proto3" json:"provider_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadProgress) Reset() {
	*x = UploadProgress{}
	mi := &file_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadProgress) ProtoMessage() {}

func (x *UploadProgress) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadProgress.ProtoReflect.Descriptor instead.
func (*UploadProgress) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{5}
}

func (x *UploadProgress) GetBytesWritten() int64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

func (x *UploadProgress) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *UploadProgress) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *UploadProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadProgress) GetProviderRef() string {
	if x != nil {
		return x.ProviderRef
	}
	return ""
}

type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// provider_ref is the ProviderRef from the final UploadProgress message
	ProviderRef string `protobuf:"bytes,1,opt,name=provider_ref,json=providerRef,proto3" json:"provider_ref,omitempty"`
	// image_name is the desired name for the registered image
	ImageName string `protobuf:"bytes,2,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	// tags to apply to the registered image
	Tags map[string]string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// provider_config_name identifies which ProviderConfig to use
	ProviderConfigName string `protobuf:"bytes,4,opt,name=provider_config_name,json=providerConfigName,proto3" json:"provider_config_name,omitempty"`
	// format of the artifact that was uploaded
	Format        string `protobuf:"bytes,5,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterRequest) GetProviderRef() string {
	if x != nil {
		return x.ProviderRef
	}
	return ""
}

func (x *RegisterRequest) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *RegisterRequest) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *RegisterRequest) GetProviderConfigName() string {
	if x != nil {
		return x.ProviderConfigName
	}
	return ""
}

func (x *RegisterRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type ImageRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // AMI-ID, Image-UUID, MOID, ...
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"` // region, datacenter, project
	Tags          map[string]string      `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageRef) Reset() {
	*x = ImageRef{}
	mi := &file_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageRef) ProtoMessage() {}

func (x *ImageRef) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageRef.ProtoReflect.Descriptor instead.
func (*ImageRef) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{7}
}

func (x *ImageRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ImageRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ImageRef) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ImageRef) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type DeleteRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ProviderRef        string                 `protobuf:"bytes,1,opt,name=provider_ref,json=providerRef,proto3" json:"provider_ref,omitempty"`
	ProviderConfigName string                 `protobuf:"bytes,2,opt,name=provider_config_name,json=providerConfigName,proto3" json:"provider_config_name,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_provider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteRequest) GetProviderRef() string {
	if x != nil {
		return x.ProviderRef
	}
	return ""
}

func (x *DeleteRequest) GetProviderConfigName() string {
	if x != nil {
		return x.ProviderConfigName
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_provider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *DeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_provider_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{10}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_provider_proto protoreflect.FileDescriptor

const file_provider_proto_rawDesc = "" +
	"\n" +
	"\x0eprovider.proto\x12\x18imagebuilder.provider.v1\"\a\n" +
	"\x05Empty\"\xcc\x01\n" +
	"\x14CapabilitiesResponse\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12)\n" +
	"\x10provider_version\x18\x02 \x01(\tR\x0fproviderVersion\x12\x18\n" +
	"\aformats\x18\x03 \x03(\tR\aformats\x12\x1f\n" +
	"\vos_families\x18\x04 \x03(\tR\n" +
	"osFamilies\x12)\n" +
	"\x10protocol_version\x18\x05 \x01(\tR\x0fprotocolVersion\"\xc9\x03\n" +
	"\x15ValidateConfigRequest\x120\n" +
	"\x14provider_config_name\x18\x01 \x01(\tR\x12providerConfigName\x12b\n" +
	"\vcredentials\x18\x02 \x03(\v2@.imagebuilder.provider.v1.ValidateConfigRequest.CredentialsEntryR\vcredentials\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x1a\n" +
	"\bendpoint\x18\x04 \x01(\tR\bendpoint\x12\x1a\n" +
	"\binsecure\x18\x05 \x01(\bR\binsecure\x12P\n" +
	"\x05extra\x18\x06 \x03(\v2:.imagebuilder.provider.v1.ValidateConfigRequest.ExtraEntryR\x05extra\x1a>\n" +
	"\x10CredentialsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"H\n" +
	"\x16ValidateConfigResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x88\x03\n" +
	"\vUploadChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04last\x18\x03 \x01(\bR\x04last\x12\x16\n" +
	"\x06format\x18\n" +
	" \x01(\tR\x06format\x12\x1a\n" +
	"\bchecksum\x18\v \x01(\tR\bchecksum\x12(\n" +
	"\x10total_size_bytes\x18\f \x01(\x03R\x0etotalSizeBytes\x12\x1b\n" +
	"\tos_family\x18\r \x01(\tR\bosFamily\x12O\n" +
	"\bmetadata\x18\x0e \x03(\v23.imagebuilder.provider.v1.UploadChunk.MetadataEntryR\bmetadata\x120\n" +
	"\x14provider_config_name\x18\x0f \x01(\tR\x12providerConfigName\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa9\x01\n" +
	"\x0eUploadProgress\x12#\n" +
	"\rbytes_written\x18\x01 \x01(\x03R\fbytesWritten\x12\x1f\n" +
	"\vtotal_bytes\x18\x02 \x01(\x03R\n" +
	"totalBytes\x12\x14\n" +
	"\x05phase\x18\x03 \x01(\tR\x05phase\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12!\n" +
	"\fprovider_ref\x18\x05 \x01(\tR\vproviderRef\"\x9f\x02\n" +
	"\x0fRegisterRequest\x12!\n" +
	"\fprovider_ref\x18\x01 \x01(\tR\vproviderRef\x12\x1d\n" +
	"\n" +
	"image_name\x18\x02 \x01(\tR\timageName\x12G\n" +
	"\x04tags\x18\x03 \x03(\v23.imagebuilder.provider.v1.RegisterRequest.TagsEntryR\x04tags\x120\n" +
	"\x14provider_config_name\x18\x04 \x01(\tR\x12providerConfigName\x12\x16\n" +
	"\x06format\x18\x05 \x01(\tR\x06format\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc5\x01\n" +
	"\bImageRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12@\n" +
	"\x04tags\x18\x04 \x03(\v2,.imagebuilder.provider.v1.ImageRef.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"d\n" +
	"\rDeleteRequest\x12!\n" +
	"\fprovider_ref\x18\x01 \x01(\tR\vproviderRef\x120\n" +
	"\x14provider_config_name\x18\x02 \x01(\tR\x12providerConfigName\"D\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"D\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xf1\x04\n" +
	"\x10PlatformProvider\x12b\n" +
	"\x0fGetCapabilities\x12\x1f.imagebuilder.provider.v1.Empty\x1a..imagebuilder.provider.v1.CapabilitiesResponse\x12s\n" +
	"\x0eValidateConfig\x12/.imagebuilder.provider.v1.ValidateConfigRequest\x1a0.imagebuilder.provider.v1.ValidateConfigResponse\x12e\n" +
	"\x0eUploadArtifact\x12%.imagebuilder.provider.v1.UploadChunk\x1a(.imagebuilder.provider.v1.UploadProgress(\x010\x01\x12^\n" +
	"\rRegisterImage\x12).imagebuilder.provider.v1.RegisterRequest\x1a\".imagebuilder.provider.v1.ImageRef\x12c\n" +
	"\x0eDeleteArtifact\x12'.imagebuilder.provider.v1.DeleteRequest\x1a(.imagebuilder.provider.v1.DeleteResponse\x12X\n" +
	"\vHealthCheck\x12\x1f.imagebuilder.provider.v1.Empty\x1a(.imagebuilder.provider.v1.HealthResponseB<Z:github.com/anwendt/imagebuilder/api/provider/v1;providerv1b\x06proto3"

var (
	file_provider_proto_rawDescOnce sync.Once
	file_provider_proto_rawDescData []byte
)

func file_provider_proto_rawDescGZIP() []byte {
	file_provider_proto_rawDescOnce.Do(func() {
		file_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_provider_proto_rawDesc), len(file_provider_proto_rawDesc)))
	})
	return file_provider_proto_rawDescData
}

var file_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_provider_proto_goTypes = []any{
	(*Empty)(nil),                  // 0: imagebuilder.provider.v1.Empty
	(*CapabilitiesResponse)(nil),   // 1: imagebuilder.provider.v1.CapabilitiesResponse
	(*ValidateConfigRequest)(nil),  // 2: imagebuilder.provider.v1.ValidateConfigRequest
	(*ValidateConfigResponse)(nil), // 3: imagebuilder.provider.v1.ValidateConfigResponse
	(*UploadChunk)(nil),            // 4: imagebuilder.provider.v1.UploadChunk
	(*UploadProgress)(nil),         // 5: imagebuilder.provider.v1.UploadProgress
	(*RegisterRequest)(nil),        // 6: imagebuilder.provider.v1.RegisterRequest
	(*ImageRef)(nil),               // 7: imagebuilder.provider.v1.ImageRef
	(*DeleteRequest)(nil),          // 8: imagebuilder.provider.v1.DeleteRequest
	(*DeleteResponse)(nil),         // 9: imagebuilder.provider.v1.DeleteResponse
	(*HealthResponse)(nil),         // 10: imagebuilder.provider.v1.HealthResponse
	nil,                            // 11: imagebuilder.provider.v1.ValidateConfigRequest.CredentialsEntry
	nil,                            // 12: imagebuilder.provider.v1.ValidateConfigRequest.ExtraEntry
	nil,                            // 13: imagebuilder.provider.v1.UploadChunk.MetadataEntry
	nil,                            // 14: imagebuilder.provider.v1.RegisterRequest.TagsEntry
	nil,                            // 15: imagebuilder.provider.v1.ImageRef.TagsEntry
}
var file_provider_proto_depIdxs = []int32{
	11, // 0: imagebuilder.provider.v1.ValidateConfigRequest.credentials:type_name -> imagebuilder.provider.v1.ValidateConfigRequest.CredentialsEntry
	12, // 1: imagebuilder.provider.v1.ValidateConfigRequest.extra:type_name -> imagebuilder.provider.v1.ValidateConfigRequest.ExtraEntry
	13, // 2: imagebuilder.provider.v1.UploadChunk.metadata:type_name -> imagebuilder.provider.v1.UploadChunk.MetadataEntry
	14, // 3: imagebuilder.provider.v1.RegisterRequest.tags:type_name -> imagebuilder.provider.v1.RegisterRequest.TagsEntry
	15, // 4: imagebuilder.provider.v1.ImageRef.tags:type_name -> imagebuilder.provider.v1.ImageRef.TagsEntry
	0,  // 5: imagebuilder.provider.v1.PlatformProvider.GetCapabilities:input_type -> imagebuilder.provider.v1.Empty
	2,  // 6: imagebuilder.provider.v1.PlatformProvider.ValidateConfig:input_type -> imagebuilder.provider.v1.ValidateConfigRequest
	4,  // 7: imagebuilder.provider.v1.PlatformProvider.UploadArtifact:input_type -> imagebuilder.provider.v1.UploadChunk
	6,  // 8: imagebuilder.provider.v1.PlatformProvider.RegisterImage:input_type -> imagebuilder.provider.v1.RegisterRequest
	8,  // 9: imagebuilder.provider.v1.PlatformProvider.DeleteArtifact:input_type -> imagebuilder.provider.v1.DeleteRequest
	0,  // 10: imagebuilder.provider.v1.PlatformProvider.HealthCheck:input_type -> imagebuilder.provider.v1.Empty
	1,  // 11: imagebuilder.provider.v1.PlatformProvider.GetCapabilities:output_type -> imagebuilder.provider.v1.CapabilitiesResponse
	3,  // 12: imagebuilder.provider.v1.PlatformProvider.ValidateConfig:output_type -> imagebuilder.provider.v1.ValidateConfigResponse
	5,  // 13: imagebuilder.provider.v1.PlatformProvider.UploadArtifact:output_type -> imagebuilder.provider.v1.UploadProgress
	7,  // 14: imagebuilder.provider.v1.PlatformProvider.RegisterImage:output_type -> imagebuilder.provider.v1.ImageRef
	9,  // 15: imagebuilder.provider.v1.PlatformProvider.DeleteArtifact:output_type -> imagebuilder.provider.v1.DeleteResponse
	10, // 16: imagebuilder.provider.v1.PlatformProvider.HealthCheck:output_type -> imagebuilder.provider.v1.HealthResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_provider_proto_init() }
func file_provider_proto_init() {
	if File_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_provider_proto_rawDesc), len(file_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_provider_proto_goTypes,
		DependencyIndexes: file_provider_proto_depIdxs,
		MessageInfos:      file_provider_proto_msgTypes,
	}.Build()
	File_provider_proto = out.File
	file_provider_proto_goTypes = nil
	file_provider_proto_depIdxs = nil
}
