// api/provider/v1/provider.proto
//
// This is the stable gRPC contract between the core operator and external
// platform provider pods. Treat field numbers as permanent — never reuse them.
//
// Breaking changes require a new package: imagebuilder.provider.v2
//
// License: Apache 2.0
//
// Generate Go code:
//   protoc --proto_path=api/provider/v1 \
//          --go_out=api/provider/v1 --go_opt=paths=source_relative \
//          --go-grpc_out=api/provider/v1 --go-grpc_opt=paths=source_relative \
//          api/provider/v1/provider.proto
//
// Or: make proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        normalized
// source: provider.proto

package providerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{0}
}

type CapabilitiesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// provider_name must match the PlatformProvider CR name e.g. "aws"
	ProviderName    string `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	ProviderVersion string `protobuf:"bytes,2,opt,name=provider_version,json=providerVersion,proto3" json:"provider_version,omitempty"` // semver e.g. "v1.2.0"
	// formats this provider can receive e.g. ["vmdk", "ova"]
	Formats []string `protobuf:"bytes,3,rep,name=formats,proto3" json:"formats,omitempty"`
	// os_families this provider supports: "linux", "windows"
	OsFamilies []string `protobuf:"bytes,4,rep,name=os_families,json=osFamilies,proto3" json:"os_families,omitempty"`
	// protocol_version of this proto schema e.g. "v1"
	// Operator rejects providers with incompatible protocol versions.
	ProtocolVersion string `protobuf:"bytes,5,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// build_modes lists execution modes supported by the provider.
	// Omitted means ["local"] for backward compatibility.
	BuildModes    []string `protobuf:"bytes,6,rep,name=build_modes,json=buildModes,proto3" json:"build_modes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesResponse) Reset() {
	*x = CapabilitiesResponse{}
	mi := &file_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesResponse) ProtoMessage() {}

func (x *CapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*CapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{1}
}

func (x *CapabilitiesResponse) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *CapabilitiesResponse) GetProviderVersion() string {
	if x != nil {
		return x.ProviderVersion
	}
	return ""
}

func (x *CapabilitiesResponse) GetFormats() []string {
	if x != nil {
		return x.Formats
	}
	return nil
}

func (x *CapabilitiesResponse) GetOsFamilies() []string {
	if x != nil {
		return x.OsFamilies
	}
	return nil
}

func (x *CapabilitiesResponse) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *CapabilitiesResponse) GetBuildModes() []string {
	if x != nil {
		return x.BuildModes
	}
	return nil
}

type RemoteBuildRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	BuildId            string                 `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	OperationRef       string                 `protobuf:"bytes,2,opt,name=operation_ref,json=operationRef,proto3" json:"operation_ref,omitempty"`
	ImageName          string                 `protobuf:"bytes,3,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	Namespace          string                 `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	OsFamily           string                 `protobuf:"bytes,5,opt,name=os_family,json=osFamily,proto3" json:"os_family,omitempty"`
	OsDistribution     string                 `protobuf:"bytes,6,opt,name=os_distribution,json=osDistribution,proto3" json:"os_distribution,omitempty"`
	OsVersion          string                 `protobuf:"bytes,7,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	OsArch             string                 `protobuf:"bytes,8,opt,name=os_arch,json=osArch,proto3" json:"os_arch,omitempty"`
	SourceType         string                 `protobuf:"bytes,9,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	SourceUrl          string                 `protobuf:"bytes,10,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
	SourceChecksum     string                 `protobuf:"bytes,11,opt,name=source_checksum,json=sourceChecksum,proto3" json:"source_checksum,omitempty"`
	ProviderConfigName string                 `protobuf:"bytes,12,opt,name=provider_config_name,json=providerConfigName,proto3" json:"provider_config_name,omitempty"`
	Format             string                 `protobuf:"bytes,13,opt,name=format,proto3" json:"format,omitempty"`
	Tags               map[string]string      `protobuf:"bytes,14,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Provisioners       []*RemoteProvisioner   `protobuf:"bytes,15,rep,name=provisioners,proto3" json:"provisioners,omitempty"`
	GuestAccess        *RemoteGuestAccess     `protobuf:"bytes,16,opt,name=guest_access,json=guestAccess,proto3" json:"guest_access,omitempty"`
	TimeoutSeconds     int64                  `protobuf:"varint,17,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	// source_provider_ref is an opaque provider-native source reference such as
	// an AMI ID, vSphere template ID, Glance UUID, or cloud image resource name.
	// Prefer this over overloading source_url for remote builds.
	SourceProviderRef string          `protobuf:"bytes,18,opt,name=source_provider_ref,json=sourceProviderRef,proto3" json:"source_provider_ref,omitempty"`
	SourceMarketplace *MarketplaceRef `protobuf:"bytes,19,opt,name=source_marketplace,json=sourceMarketplace,proto3" json:"source_marketplace,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RemoteBuildRequest) Reset() {
	*x = RemoteBuildRequest{}
	mi := &file_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteBuildRequest) ProtoMessage() {}

func (x *RemoteBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteBuildRequest.ProtoReflect.Descriptor instead.
func (*RemoteBuildRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{2}
}

func (x *RemoteBuildRequest) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *RemoteBuildRequest) GetOperationRef() string {
	if x != nil {
		return x.OperationRef
	}
	return ""
}

func (x *RemoteBuildRequest) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *RemoteBuildRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RemoteBuildRequest) GetOsFamily() string {
	if x != nil {
		return x.OsFamily
	}
	return ""
}

func (x *RemoteBuildRequest) GetOsDistribution() string {
	if x != nil {
		return x.OsDistribution
	}
	return ""
}

func (x *RemoteBuildRequest) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *RemoteBuildRequest) GetOsArch() string {
	if x != nil {
		return x.OsArch
	}
	return ""
}

func (x *RemoteBuildRequest) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *RemoteBuildRequest) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

func (x *RemoteBuildRequest) GetSourceChecksum() string {
	if x != nil {
		return x.SourceChecksum
	}
	return ""
}

func (x *RemoteBuildRequest) GetProviderConfigName() string {
	if x != nil {
		return x.ProviderConfigName
	}
	return ""
}

func (x *RemoteBuildRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *RemoteBuildRequest) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *RemoteBuildRequest) GetProvisioners() []*RemoteProvisioner {
	if x != nil {
		return x.Provisioners
	}
	return nil
}

func (x *RemoteBuildRequest) GetGuestAccess() *RemoteGuestAccess {
	if x != nil {
		return x.GuestAccess
	}
	return nil
}

func (x *RemoteBuildRequest) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *RemoteBuildRequest) GetSourceProviderRef() string {
	if x != nil {
		return x.SourceProviderRef
	}
	return ""
}

func (x *RemoteBuildRequest) GetSourceMarketplace() *MarketplaceRef {
	if x != nil {
		return x.SourceMarketplace
	}
	return nil
}

type MarketplaceRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Publisher     string                 `protobuf:"bytes,1,opt,name=publisher,proto3" json:"publisher,omitempty"`
	Offer         string                 `protobuf:"bytes,2,opt,name=offer,proto3" json:"offer,omitempty"`
	Sku           string                 `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketplaceRef) Reset() {
	*x = MarketplaceRef{}
	mi := &file_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketplaceRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketplaceRef) ProtoMessage() {}

func (x *MarketplaceRef) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketplaceRef.ProtoReflect.Descriptor instead.
func (*MarketplaceRef) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{3}
}

func (x *MarketplaceRef) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

func (x *MarketplaceRef) GetOffer() string {
	if x != nil {
		return x.Offer
	}
	return ""
}

func (x *MarketplaceRef) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *MarketplaceRef) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type RemoteProvisioner struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Type          string                   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Image         string                   `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Inline        string                   `protobuf:"bytes,3,opt,name=inline,proto3" json:"inline,omitempty"`
	Playbook      string                   `protobuf:"bytes,4,opt,name=playbook,proto3" json:"playbook,omitempty"`
	Args          []string                 `protobuf:"bytes,5,rep,name=args,proto3" json:"args,omitempty"`
	ExtraVars     map[string]string        `protobuf:"bytes,6,rep,name=extra_vars,json=extraVars,proto3" json:"extra_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Source        *RemoteProvisionerSource `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteProvisioner) Reset() {
	*x = RemoteProvisioner{}
	mi := &file_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteProvisioner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteProvisioner) ProtoMessage() {}

func (x *RemoteProvisioner) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteProvisioner.ProtoReflect.Descriptor instead.
func (*RemoteProvisioner) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{4}
}

func (x *RemoteProvisioner) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RemoteProvisioner) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *RemoteProvisioner) GetInline() string {
	if x != nil {
		return x.Inline
	}
	return ""
}

func (x *RemoteProvisioner) GetPlaybook() string {
	if x != nil {
		return x.Playbook
	}
	return ""
}

func (x *RemoteProvisioner) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *RemoteProvisioner) GetExtraVars() map[string]string {
	if x != nil {
		return x.ExtraVars
	}
	return nil
}

func (x *RemoteProvisioner) GetSource() *RemoteProvisionerSource {
	if x != nil {
		return x.Source
	}
	return nil
}

type RemoteProvisionerSource struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Git           *RemoteGitProvisionerSource `protobuf:"bytes,1,opt,name=git,proto3" json:"git,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteProvisionerSource) Reset() {
	*x = RemoteProvisionerSource{}
	mi := &file_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteProvisionerSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteProvisionerSource) ProtoMessage() {}

func (x *RemoteProvisionerSource) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteProvisionerSource.ProtoReflect.Descriptor instead.
func (*RemoteProvisionerSource) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{5}
}

func (x *RemoteProvisionerSource) GetGit() *RemoteGitProvisionerSource {
	if x != nil {
		return x.Git
	}
	return nil
}

type RemoteGitProvisionerSource struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Url           string                    `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Ref           string                    `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	Path          string                    `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Auth          *RemoteGitProvisionerAuth `protobuf:"bytes,4,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteGitProvisionerSource) Reset() {
	*x = RemoteGitProvisionerSource{}
	mi := &file_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteGitProvisionerSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteGitProvisionerSource) ProtoMessage() {}

func (x *RemoteGitProvisionerSource) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteGitProvisionerSource.ProtoReflect.Descriptor instead.
func (*RemoteGitProvisionerSource) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{6}
}

func (x *RemoteGitProvisionerSource) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *RemoteGitProvisionerSource) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *RemoteGitProvisionerSource) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RemoteGitProvisionerSource) GetAuth() *RemoteGitProvisionerAuth {
	if x != nil {
		return x.Auth
	}
	return nil
}

type RemoteGitProvisionerAuth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteGitProvisionerAuth) Reset() {
	*x = RemoteGitProvisionerAuth{}
	mi := &file_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteGitProvisionerAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteGitProvisionerAuth) ProtoMessage() {}

func (x *RemoteGitProvisionerAuth) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteGitProvisionerAuth.ProtoReflect.Descriptor instead.
func (*RemoteGitProvisionerAuth) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{7}
}

func (x *RemoteGitProvisionerAuth) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RemoteGitProvisionerAuth) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RemoteGitProvisionerAuth) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RemoteGuestAccess struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Protocol          string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	User              string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	GuestPort         int32                  `protobuf:"varint,3,opt,name=guest_port,json=guestPort,proto3" json:"guest_port,omitempty"`
	GeneratedSshKey   bool                   `protobuf:"varint,4,opt,name=generated_ssh_key,json=generatedSshKey,proto3" json:"generated_ssh_key,omitempty"`
	GeneratedPassword bool                   `protobuf:"varint,5,opt,name=generated_password,json=generatedPassword,proto3" json:"generated_password,omitempty"`
	InjectionMethod   string                 `protobuf:"bytes,6,opt,name=injection_method,json=injectionMethod,proto3" json:"injection_method,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RemoteGuestAccess) Reset() {
	*x = RemoteGuestAccess{}
	mi := &file_provider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteGuestAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteGuestAccess) ProtoMessage() {}

func (x *RemoteGuestAccess) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteGuestAccess.ProtoReflect.Descriptor instead.
func (*RemoteGuestAccess) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{8}
}

func (x *RemoteGuestAccess) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *RemoteGuestAccess) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *RemoteGuestAccess) GetGuestPort() int32 {
	if x != nil {
		return x.GuestPort
	}
	return 0
}

func (x *RemoteGuestAccess) GetGeneratedSshKey() bool {
	if x != nil {
		return x.GeneratedSshKey
	}
	return false
}

func (x *RemoteGuestAccess) GetGeneratedPassword() bool {
	if x != nil {
		return x.GeneratedPassword
	}
	return false
}

func (x *RemoteGuestAccess) GetInjectionMethod() string {
	if x != nil {
		return x.InjectionMethod
	}
	return ""
}

type RemoteBuildResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationRef  string                 `protobuf:"bytes,1,opt,name=operation_ref,json=operationRef,proto3" json:"operation_ref,omitempty"`
	Phase         string                 `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Done          bool                   `protobuf:"varint,4,opt,name=done,proto3" json:"done,omitempty"`
	Images        []*RemoteImageRef      `protobuf:"bytes,5,rep,name=images,proto3" json:"images,omitempty"`
	Artifact      *RemoteArtifact        `protobuf:"bytes,6,opt,name=artifact,proto3" json:"artifact,omitempty"`
	Hygiene       *RemoteHygieneResult   `protobuf:"bytes,7,opt,name=hygiene,proto3" json:"hygiene,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteBuildResponse) Reset() {
	*x = RemoteBuildResponse{}
	mi := &file_provider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteBuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteBuildResponse) ProtoMessage() {}

func (x *RemoteBuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteBuildResponse.ProtoReflect.Descriptor instead.
func (*RemoteBuildResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{9}
}

func (x *RemoteBuildResponse) GetOperationRef() string {
	if x != nil {
		return x.OperationRef
	}
	return ""
}

func (x *RemoteBuildResponse) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *RemoteBuildResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RemoteBuildResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *RemoteBuildResponse) GetImages() []*RemoteImageRef {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *RemoteBuildResponse) GetArtifact() *RemoteArtifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

func (x *RemoteBuildResponse) GetHygiene() *RemoteHygieneResult {
	if x != nil {
		return x.Hygiene
	}
	return nil
}

type RemoteHygieneResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status is provider-neutral and should be "passed", "failed", or "unknown".
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// message is copied into VMImage status/events and must not contain secrets.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// checks contains provider-neutral check identifiers such as
	// "temporary-user-removed" or "bootstrap-files-removed".
	Checks []string `protobuf:"bytes,3,rep,name=checks,proto3" json:"checks,omitempty"`
	// result_ref is an optional non-secret provider/workspace reference to a
	// detailed hygiene report.
	ResultRef     string `protobuf:"bytes,4,opt,name=result_ref,json=resultRef,proto3" json:"result_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteHygieneResult) Reset() {
	*x = RemoteHygieneResult{}
	mi := &file_provider_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteHygieneResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteHygieneResult) ProtoMessage() {}

func (x *RemoteHygieneResult) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteHygieneResult.ProtoReflect.Descriptor instead.
func (*RemoteHygieneResult) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{10}
}

func (x *RemoteHygieneResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RemoteHygieneResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RemoteHygieneResult) GetChecks() []string {
	if x != nil {
		return x.Checks
	}
	return nil
}

func (x *RemoteHygieneResult) GetResultRef() string {
	if x != nil {
		return x.ResultRef
	}
	return ""
}

type RemoteImageRef struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Provider           string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	ProviderConfigName string                 `protobuf:"bytes,2,opt,name=provider_config_name,json=providerConfigName,proto3" json:"provider_config_name,omitempty"`
	ImageRef           string                 `protobuf:"bytes,3,opt,name=image_ref,json=imageRef,proto3" json:"image_ref,omitempty"`
	ImageName          string                 `protobuf:"bytes,4,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	Location           string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	Format             string                 `protobuf:"bytes,6,opt,name=format,proto3" json:"format,omitempty"`
	Checksum           string                 `protobuf:"bytes,7,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Tags               map[string]string      `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RemoteImageRef) Reset() {
	*x = RemoteImageRef{}
	mi := &file_provider_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteImageRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteImageRef) ProtoMessage() {}

func (x *RemoteImageRef) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteImageRef.ProtoReflect.Descriptor instead.
func (*RemoteImageRef) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{11}
}

func (x *RemoteImageRef) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *RemoteImageRef) GetProviderConfigName() string {
	if x != nil {
		return x.ProviderConfigName
	}
	return ""
}

func (x *RemoteImageRef) GetImageRef() string {
	if x != nil {
		return x.ImageRef
	}
	return ""
}

func (x *RemoteImageRef) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *RemoteImageRef) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *RemoteImageRef) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *RemoteImageRef) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *RemoteImageRef) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type RemoteArtifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	Checksum      string                 `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	OsFamily      string                 `protobuf:"bytes,5,opt,name=os_family,json=osFamily,proto3" json:"os_family,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteArtifact) Reset() {
	*x = RemoteArtifact{}
	mi := &file_provider_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteArtifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteArtifact) ProtoMessage() {}

func (x *RemoteArtifact) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteArtifact.ProtoReflect.Descriptor instead.
func (*RemoteArtifact) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{12}
}

func (x *RemoteArtifact) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RemoteArtifact) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *RemoteArtifact) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *RemoteArtifact) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *RemoteArtifact) GetOsFamily() string {
	if x != nil {
		return x.OsFamily
	}
	return ""
}

func (x *RemoteArtifact) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type RemoteBuildCleanupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cleaned       bool                   `protobuf:"varint,1,opt,name=cleaned,proto3" json:"cleaned,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteBuildCleanupResponse) Reset() {
	*x = RemoteBuildCleanupResponse{}
	mi := &file_provider_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteBuildCleanupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteBuildCleanupResponse) ProtoMessage() {}

func (x *RemoteBuildCleanupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteBuildCleanupResponse.ProtoReflect.Descriptor instead.
func (*RemoteBuildCleanupResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{13}
}

func (x *RemoteBuildCleanupResponse) GetCleaned() bool {
	if x != nil {
		return x.Cleaned
	}
	return false
}

func (x *RemoteBuildCleanupResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ValidateConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// provider_config_name is the name of the ProviderConfig CR
	ProviderConfigName string `protobuf:"bytes,1,opt,name=provider_config_name,json=providerConfigName,proto3" json:"provider_config_name,omitempty"`
	// credentials is the decoded secret content
	Credentials map[string][]byte `protobuf:"bytes,2,rep,name=credentials,proto3" json:"credentials,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// region / endpoint from ProviderConfigSpec
	Region   string `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	Endpoint string `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Insecure bool   `protobuf:"varint,5,opt,name=insecure,proto3" json:"insecure,omitempty"`
	// extra holds provider-specific key-value config
	Extra         map[string]string `protobuf:"bytes,6,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateConfigRequest) Reset() {
	*x = ValidateConfigRequest{}
	mi := &file_provider_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateConfigRequest) ProtoMessage() {}

func (x *ValidateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateConfigRequest.ProtoReflect.Descriptor instead.
func (*ValidateConfigRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{14}
}

func (x *ValidateConfigRequest) GetProviderConfigName() string {
	if x != nil {
		return x.ProviderConfigName
	}
	return ""
}

func (x *ValidateConfigRequest) GetCredentials() map[string][]byte {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *ValidateConfigRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ValidateConfigRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *ValidateConfigRequest) GetInsecure() bool {
	if x != nil {
		return x.Insecure
	}
	return false
}

func (x *ValidateConfigRequest) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

type ValidateConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // human-readable error when valid=false
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateConfigResponse) Reset() {
	*x = ValidateConfigResponse{}
	mi := &file_provider_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateConfigResponse) ProtoMessage() {}

func (x *ValidateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateConfigResponse.ProtoReflect.Descriptor instead.
func (*ValidateConfigResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{15}
}

func (x *ValidateConfigResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UploadChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// data is the raw bytes of this chunk
	Data   []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Offset int64  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Last   bool   `protobuf:"varint,3,opt,name=last,proto3" json:"last,omitempty"` // true on the final chunk
	// These fields are only populated in the FIRST chunk (offset=0)
	Format         string            `protobuf:"bytes,10,opt,name=format,proto3" json:"format,omitempty"`     // ImageFormat e.g. "vmdk"
	Checksum       string            `protobuf:"bytes,11,opt,name=checksum,proto3" json:"checksum,omitempty"` // sha256:hex of the complete artifact
	TotalSizeBytes int64             `protobuf:"varint,12,opt,name=total_size_bytes,json=totalSizeBytes,proto3" json:"total_size_bytes,omitempty"`
	OsFamily       string            `protobuf:"bytes,13,opt,name=os_family,json=osFamily,proto3" json:"os_family,omitempty"`
	Metadata       map[string]string `protobuf:"bytes,14,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// provider_config_name identifies which ProviderConfig to use
	ProviderConfigName string `protobuf:"bytes,15,opt,name=provider_config_name,json=providerConfigName,proto3" json:"provider_config_name,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UploadChunk) Reset() {
	*x = UploadChunk{}
	mi := &file_provider_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadChunk) ProtoMessage() {}

func (x *UploadChunk) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadChunk.ProtoReflect.Descriptor instead.
func (*UploadChunk) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{16}
}

func (x *UploadChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *UploadChunk) GetLast() bool {
	if x != nil {
		return x.Last
	}
	return false
}

func (x *UploadChunk) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *UploadChunk) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *UploadChunk) GetTotalSizeBytes() int64 {
	if x != nil {
		return x.TotalSizeBytes
	}
	return 0
}

func (x *UploadChunk) GetOsFamily() string {
	if x != nil {
		return x.OsFamily
	}
	return ""
}

func (x *UploadChunk) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UploadChunk) GetProviderConfigName() string {
	if x != nil {
		return x.ProviderConfigName
	}
	return ""
}

type UploadProgress struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	BytesWritten int64                  `protobuf:"varint,1,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	TotalBytes   int64                  `protobuf:"varint,2,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	Phase        string                 `protobuf:"bytes,3,opt,name=phase,proto3" json:"phase,omitempty"` // "uploading" | "converting" | "verifying"
	Message      string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// provider_ref is set in the final progress message (phase="done")
	// It is passed back to RegisterImage.
	ProviderRef   string `protobuf:"bytes,5,opt,name=provider_ref,json=providerRef,proto3" json:"provider_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadProgress) Reset() {
	*x = UploadProgress{}
	mi := &file_provider_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadProgress) ProtoMessage() {}

func (x *UploadProgress) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadProgress.ProtoReflect.Descriptor instead.
func (*UploadProgress) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{17}
}

func (x *UploadProgress) GetBytesWritten() int64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

func (x *UploadProgress) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *UploadProgress) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *UploadProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadProgress) GetProviderRef() string {
	if x != nil {
		return x.ProviderRef
	}
	return ""
}

type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// provider_ref is the ProviderRef from the final UploadProgress message
	ProviderRef string `protobuf:"bytes,1,opt,name=provider_ref,json=providerRef,proto3" json:"provider_ref,omitempty"`
	// image_name is the desired name for the registered image
	ImageName string `protobuf:"bytes,2,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	// tags to apply to the registered image
	Tags map[string]string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// provider_config_name identifies which ProviderConfig to use
	ProviderConfigName string `protobuf:"bytes,4,opt,name=provider_config_name,json=providerConfigName,proto3" json:"provider_config_name,omitempty"`
	// format of the artifact that was uploaded
	Format        string `protobuf:"bytes,5,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_provider_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{18}
}

func (x *RegisterRequest) GetProviderRef() string {
	if x != nil {
		return x.ProviderRef
	}
	return ""
}

func (x *RegisterRequest) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *RegisterRequest) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *RegisterRequest) GetProviderConfigName() string {
	if x != nil {
		return x.ProviderConfigName
	}
	return ""
}

func (x *RegisterRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type ImageRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // AMI-ID, Image-UUID, MOID, ...
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"` // region, datacenter, project
	Tags          map[string]string      `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageRef) Reset() {
	*x = ImageRef{}
	mi := &file_provider_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageRef) ProtoMessage() {}

func (x *ImageRef) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageRef.ProtoReflect.Descriptor instead.
func (*ImageRef) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{19}
}

func (x *ImageRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ImageRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ImageRef) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ImageRef) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type DeleteRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ProviderRef        string                 `protobuf:"bytes,1,opt,name=provider_ref,json=providerRef,proto3" json:"provider_ref,omitempty"`
	ProviderConfigName string                 `protobuf:"bytes,2,opt,name=provider_config_name,json=providerConfigName,proto3" json:"provider_config_name,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_provider_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteRequest) GetProviderRef() string {
	if x != nil {
		return x.ProviderRef
	}
	return ""
}

func (x *DeleteRequest) GetProviderConfigName() string {
	if x != nil {
		return x.ProviderConfigName
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_provider_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *DeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_provider_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{22}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_provider_proto protoreflect.FileDescriptor

const file_provider_proto_rawDesc = "" +
	"\n" +
	"\x0eprovider.proto\x12\x18imagebuilder.provider.v1\"\a\n" +
	"\x05Empty\"\xed\x01\n" +
	"\x14CapabilitiesResponse\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12)\n" +
	"\x10provider_version\x18\x02 \x01(\tR\x0fproviderVersion\x12\x18\n" +
	"\aformats\x18\x03 \x03(\tR\aformats\x12\x1f\n" +
	"\vos_families\x18\x04 \x03(\tR\n" +
	"osFamilies\x12)\n" +
	"\x10protocol_version\x18\x05 \x01(\tR\x0fprotocolVersion\x12\x1f\n" +
	"\vbuild_modes\x18\x06 \x03(\tR\n" +
	"buildModes\"\x9a\a\n" +
	"\x12RemoteBuildRequest\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\x12#\n" +
	"\roperation_ref\x18\x02 \x01(\tR\foperationRef\x12\x1d\n" +
	"\n" +
	"image_name\x18\x03 \x01(\tR\timageName\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12\x1b\n" +
	"\tos_family\x18\x05 \x01(\tR\bosFamily\x12'\n" +
	"\x0fos_distribution\x18\x06 \x01(\tR\x0eosDistribution\x12\x1d\n" +
	"\n" +
	"os_version\x18\a \x01(\tR\tosVersion\x12\x17\n" +
	"\aos_arch\x18\b \x01(\tR\x06osArch\x12\x1f\n" +
	"\vsource_type\x18\t \x01(\tR\n" +
	"sourceType\x12\x1d\n" +
	"\n" +
	"source_url\x18\n" +
	" \x01(\tR\tsourceUrl\x12'\n" +
	"\x0fsource_checksum\x18\v \x01(\tR\x0esourceChecksum\x120\n" +
	"\x14provider_config_name\x18\f \x01(\tR\x12providerConfigName\x12\x16\n" +
	"\x06format\x18\r \x01(\tR\x06format\x12J\n" +
	"\x04tags\x18\x0e \x03(\v26.imagebuilder.provider.v1.RemoteBuildRequest.TagsEntryR\x04tags\x12O\n" +
	"\fprovisioners\x18\x0f \x03(\v2+.imagebuilder.provider.v1.RemoteProvisionerR\fprovisioners\x12N\n" +
	"\fguest_access\x18\x10 \x01(\v2+.imagebuilder.provider.v1.RemoteGuestAccessR\vguestAccess\x12'\n" +
	"\x0ftimeout_seconds\x18\x11 \x01(\x03R\x0etimeoutSeconds\x12.\n" +
	"\x13source_provider_ref\x18\x12 \x01(\tR\x11sourceProviderRef\x12W\n" +
	"\x12source_marketplace\x18\x13 \x01(\v2(.imagebuilder.provider.v1.MarketplaceRefR\x11sourceMarketplace\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"p\n" +
	"\x0eMarketplaceRef\x12\x1c\n" +
	"\tpublisher\x18\x01 \x01(\tR\tpublisher\x12\x14\n" +
	"\x05offer\x18\x02 \x01(\tR\x05offer\x12\x10\n" +
	"\x03sku\x18\x03 \x01(\tR\x03sku\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"\xe9\x02\n" +
	"\x11RemoteProvisioner\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x16\n" +
	"\x06inline\x18\x03 \x01(\tR\x06inline\x12\x1a\n" +
	"\bplaybook\x18\x04 \x01(\tR\bplaybook\x12\x12\n" +
	"\x04args\x18\x05 \x03(\tR\x04args\x12Y\n" +
	"\n" +
	"extra_vars\x18\x06 \x03(\v2:.imagebuilder.provider.v1.RemoteProvisioner.ExtraVarsEntryR\textraVars\x12I\n" +
	"\x06source\x18\a \x01(\v21.imagebuilder.provider.v1.RemoteProvisionerSourceR\x06source\x1a<\n" +
	"\x0eExtraVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"a\n" +
	"\x17RemoteProvisionerSource\x12F\n" +
	"\x03git\x18\x01 \x01(\v24.imagebuilder.provider.v1.RemoteGitProvisionerSourceR\x03git\"\x9c\x01\n" +
	"\x1aRemoteGitProvisionerSource\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x10\n" +
	"\x03ref\x18\x02 \x01(\tR\x03ref\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12F\n" +
	"\x04auth\x18\x04 \x01(\v22.imagebuilder.provider.v1.RemoteGitProvisionerAuthR\x04auth\"h\n" +
	"\x18RemoteGitProvisionerAuth\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"\xe8\x01\n" +
	"\x11RemoteGuestAccess\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x1d\n" +
	"\n" +
	"guest_port\x18\x03 \x01(\x05R\tguestPort\x12*\n" +
	"\x11generated_ssh_key\x18\x04 \x01(\bR\x0fgeneratedSshKey\x12-\n" +
	"\x12generated_password\x18\x05 \x01(\bR\x11generatedPassword\x12)\n" +
	"\x10injection_method\x18\x06 \x01(\tR\x0finjectionMethod\"\xcf\x02\n" +
	"\x13RemoteBuildResponse\x12#\n" +
	"\roperation_ref\x18\x01 \x01(\tR\foperationRef\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x12\n" +
	"\x04done\x18\x04 \x01(\bR\x04done\x12@\n" +
	"\x06images\x18\x05 \x03(\v2(.imagebuilder.provider.v1.RemoteImageRefR\x06images\x12D\n" +
	"\bartifact\x18\x06 \x01(\v2(.imagebuilder.provider.v1.RemoteArtifactR\bartifact\x12G\n" +
	"\ahygiene\x18\a \x01(\v2-.imagebuilder.provider.v1.RemoteHygieneResultR\ahygiene\"~\n" +
	"\x13RemoteHygieneResult\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06checks\x18\x03 \x03(\tR\x06checks\x12\x1d\n" +
	"\n" +
	"result_ref\x18\x04 \x01(\tR\tresultRef\"\xeb\x02\n" +
	"\x0eRemoteImageRef\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x120\n" +
	"\x14provider_config_name\x18\x02 \x01(\tR\x12providerConfigName\x12\x1b\n" +
	"\timage_ref\x18\x03 \x01(\tR\bimageRef\x12\x1d\n" +
	"\n" +
	"image_name\x18\x04 \x01(\tR\timageName\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x12\x16\n" +
	"\x06format\x18\x06 \x01(\tR\x06format\x12\x1a\n" +
	"\bchecksum\x18\a \x01(\tR\bchecksum\x12F\n" +
	"\x04tags\x18\b \x03(\v22.imagebuilder.provider.v1.RemoteImageRef.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa5\x02\n" +
	"\x0eRemoteArtifact\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12\x1a\n" +
	"\bchecksum\x18\x03 \x01(\tR\bchecksum\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\x12\x1b\n" +
	"\tos_family\x18\x05 \x01(\tR\bosFamily\x12R\n" +
	"\bmetadata\x18\x06 \x03(\v26.imagebuilder.provider.v1.RemoteArtifact.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"P\n" +
	"\x1aRemoteBuildCleanupResponse\x12\x18\n" +
	"\acleaned\x18\x01 \x01(\bR\acleaned\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc9\x03\n" +
	"\x15ValidateConfigRequest\x120\n" +
	"\x14provider_config_name\x18\x01 \x01(\tR\x12providerConfigName\x12b\n" +
	"\vcredentials\x18\x02 \x03(\v2@.imagebuilder.provider.v1.ValidateConfigRequest.CredentialsEntryR\vcredentials\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x1a\n" +
	"\bendpoint\x18\x04 \x01(\tR\bendpoint\x12\x1a\n" +
	"\binsecure\x18\x05 \x01(\bR\binsecure\x12P\n" +
	"\x05extra\x18\x06 \x03(\v2:.imagebuilder.provider.v1.ValidateConfigRequest.ExtraEntryR\x05extra\x1a>\n" +
	"\x10CredentialsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"H\n" +
	"\x16ValidateConfigResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x88\x03\n" +
	"\vUploadChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04last\x18\x03 \x01(\bR\x04last\x12\x16\n" +
	"\x06format\x18\n" +
	" \x01(\tR\x06format\x12\x1a\n" +
	"\bchecksum\x18\v \x01(\tR\bchecksum\x12(\n" +
	"\x10total_size_bytes\x18\f \x01(\x03R\x0etotalSizeBytes\x12\x1b\n" +
	"\tos_family\x18\r \x01(\tR\bosFamily\x12O\n" +
	"\bmetadata\x18\x0e \x03(\v23.imagebuilder.provider.v1.UploadChunk.MetadataEntryR\bmetadata\x120\n" +
	"\x14provider_config_name\x18\x0f \x01(\tR\x12providerConfigName\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa9\x01\n" +
	"\x0eUploadProgress\x12#\n" +
	"\rbytes_written\x18\x01 \x01(\x03R\fbytesWritten\x12\x1f\n" +
	"\vtotal_bytes\x18\x02 \x01(\x03R\n" +
	"totalBytes\x12\x14\n" +
	"\x05phase\x18\x03 \x01(\tR\x05phase\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12!\n" +
	"\fprovider_ref\x18\x05 \x01(\tR\vproviderRef\"\x9f\x02\n" +
	"\x0fRegisterRequest\x12!\n" +
	"\fprovider_ref\x18\x01 \x01(\tR\vproviderRef\x12\x1d\n" +
	"\n" +
	"image_name\x18\x02 \x01(\tR\timageName\x12G\n" +
	"\x04tags\x18\x03 \x03(\v23.imagebuilder.provider.v1.RegisterRequest.TagsEntryR\x04tags\x120\n" +
	"\x14provider_config_name\x18\x04 \x01(\tR\x12providerConfigName\x12\x16\n" +
	"\x06format\x18\x05 \x01(\tR\x06format\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc5\x01\n" +
	"\bImageRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12@\n" +
	"\x04tags\x18\x04 \x03(\v2,.imagebuilder.provider.v1.ImageRef.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"d\n" +
	"\rDeleteRequest\x12!\n" +
	"\fprovider_ref\x18\x01 \x01(\tR\vproviderRef\x120\n" +
	"\x14provider_config_name\x18\x02 \x01(\tR\x12providerConfigName\"D\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"D\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xe0\x06\n" +
	"\x10PlatformProvider\x12b\n" +
	"\x0fGetCapabilities\x12\x1f.imagebuilder.provider.v1.Empty\x1a..imagebuilder.provider.v1.CapabilitiesResponse\x12s\n" +
	"\x0eValidateConfig\x12/.imagebuilder.provider.v1.ValidateConfigRequest\x1a0.imagebuilder.provider.v1.ValidateConfigResponse\x12e\n" +
	"\x0eUploadArtifact\x12%.imagebuilder.provider.v1.UploadChunk\x1a(.imagebuilder.provider.v1.UploadProgress(\x010\x01\x12^\n" +
	"\rRegisterImage\x12).imagebuilder.provider.v1.RegisterRequest\x1a\".imagebuilder.provider.v1.ImageRef\x12c\n" +
	"\x0eDeleteArtifact\x12'.imagebuilder.provider.v1.DeleteRequest\x1a(.imagebuilder.provider.v1.DeleteResponse\x12X\n" +
	"\vHealthCheck\x12\x1f.imagebuilder.provider.v1.Empty\x1a(.imagebuilder.provider.v1.HealthResponse\x12s\n" +
	"\x14ReconcileRemoteBuild\x12,.imagebuilder.provider.v1.RemoteBuildRequest\x1a-.imagebuilder.provider.v1.RemoteBuildResponse\x12x\n" +
	"\x12CleanupRemoteBuild\x12,.imagebuilder.provider.v1.RemoteBuildRequest\x1a4.imagebuilder.provider.v1.RemoteBuildCleanupResponseB<Z:github.com/anwendt/imagebuilder/api/provider/v1;providerv1b\x06proto3"

var (
	file_provider_proto_rawDescOnce sync.Once
	file_provider_proto_rawDescData []byte
)

func file_provider_proto_rawDescGZIP() []byte {
	file_provider_proto_rawDescOnce.Do(func() {
		file_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_provider_proto_rawDesc), len(file_provider_proto_rawDesc)))
	})
	return file_provider_proto_rawDescData
}

var file_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_provider_proto_goTypes = []any{
	(*Empty)(nil),                      // 0: imagebuilder.provider.v1.Empty
	(*CapabilitiesResponse)(nil),       // 1: imagebuilder.provider.v1.CapabilitiesResponse
	(*RemoteBuildRequest)(nil),         // 2: imagebuilder.provider.v1.RemoteBuildRequest
	(*MarketplaceRef)(nil),             // 3: imagebuilder.provider.v1.MarketplaceRef
	(*RemoteProvisioner)(nil),          // 4: imagebuilder.provider.v1.RemoteProvisioner
	(*RemoteProvisionerSource)(nil),    // 5: imagebuilder.provider.v1.RemoteProvisionerSource
	(*RemoteGitProvisionerSource)(nil), // 6: imagebuilder.provider.v1.RemoteGitProvisionerSource
	(*RemoteGitProvisionerAuth)(nil),   // 7: imagebuilder.provider.v1.RemoteGitProvisionerAuth
	(*RemoteGuestAccess)(nil),          // 8: imagebuilder.provider.v1.RemoteGuestAccess
	(*RemoteBuildResponse)(nil),        // 9: imagebuilder.provider.v1.RemoteBuildResponse
	(*RemoteHygieneResult)(nil),        // 10: imagebuilder.provider.v1.RemoteHygieneResult
	(*RemoteImageRef)(nil),             // 11: imagebuilder.provider.v1.RemoteImageRef
	(*RemoteArtifact)(nil),             // 12: imagebuilder.provider.v1.RemoteArtifact
	(*RemoteBuildCleanupResponse)(nil), // 13: imagebuilder.provider.v1.RemoteBuildCleanupResponse
	(*ValidateConfigRequest)(nil),      // 14: imagebuilder.provider.v1.ValidateConfigRequest
	(*ValidateConfigResponse)(nil),     // 15: imagebuilder.provider.v1.ValidateConfigResponse
	(*UploadChunk)(nil),                // 16: imagebuilder.provider.v1.UploadChunk
	(*UploadProgress)(nil),             // 17: imagebuilder.provider.v1.UploadProgress
	(*RegisterRequest)(nil),            // 18: imagebuilder.provider.v1.RegisterRequest
	(*ImageRef)(nil),                   // 19: imagebuilder.provider.v1.ImageRef
	(*DeleteRequest)(nil),              // 20: imagebuilder.provider.v1.DeleteRequest
	(*DeleteResponse)(nil),             // 21: imagebuilder.provider.v1.DeleteResponse
	(*HealthResponse)(nil),             // 22: imagebuilder.provider.v1.HealthResponse
	nil,                                // 23: imagebuilder.provider.v1.RemoteBuildRequest.TagsEntry
	nil,                                // 24: imagebuilder.provider.v1.RemoteProvisioner.ExtraVarsEntry
	nil,                                // 25: imagebuilder.provider.v1.RemoteImageRef.TagsEntry
	nil,                                // 26: imagebuilder.provider.v1.RemoteArtifact.MetadataEntry
	nil,                                // 27: imagebuilder.provider.v1.ValidateConfigRequest.CredentialsEntry
	nil,                                // 28: imagebuilder.provider.v1.ValidateConfigRequest.ExtraEntry
	nil,                                // 29: imagebuilder.provider.v1.UploadChunk.MetadataEntry
	nil,                                // 30: imagebuilder.provider.v1.RegisterRequest.TagsEntry
	nil,                                // 31: imagebuilder.provider.v1.ImageRef.TagsEntry
}
var file_provider_proto_depIdxs = []int32{
	23, // 0: imagebuilder.provider.v1.RemoteBuildRequest.tags:type_name -> imagebuilder.provider.v1.RemoteBuildRequest.TagsEntry
	4,  // 1: imagebuilder.provider.v1.RemoteBuildRequest.provisioners:type_name -> imagebuilder.provider.v1.RemoteProvisioner
	8,  // 2: imagebuilder.provider.v1.RemoteBuildRequest.guest_access:type_name -> imagebuilder.provider.v1.RemoteGuestAccess
	3,  // 3: imagebuilder.provider.v1.RemoteBuildRequest.source_marketplace:type_name -> imagebuilder.provider.v1.MarketplaceRef
	24, // 4: imagebuilder.provider.v1.RemoteProvisioner.extra_vars:type_name -> imagebuilder.provider.v1.RemoteProvisioner.ExtraVarsEntry
	5,  // 5: imagebuilder.provider.v1.RemoteProvisioner.source:type_name -> imagebuilder.provider.v1.RemoteProvisionerSource
	6,  // 6: imagebuilder.provider.v1.RemoteProvisionerSource.git:type_name -> imagebuilder.provider.v1.RemoteGitProvisionerSource
	7,  // 7: imagebuilder.provider.v1.RemoteGitProvisionerSource.auth:type_name -> imagebuilder.provider.v1.RemoteGitProvisionerAuth
	11, // 8: imagebuilder.provider.v1.RemoteBuildResponse.images:type_name -> imagebuilder.provider.v1.RemoteImageRef
	12, // 9: imagebuilder.provider.v1.RemoteBuildResponse.artifact:type_name -> imagebuilder.provider.v1.RemoteArtifact
	10, // 10: imagebuilder.provider.v1.RemoteBuildResponse.hygiene:type_name -> imagebuilder.provider.v1.RemoteHygieneResult
	25, // 11: imagebuilder.provider.v1.RemoteImageRef.tags:type_name -> imagebuilder.provider.v1.RemoteImageRef.TagsEntry
	26, // 12: imagebuilder.provider.v1.RemoteArtifact.metadata:type_name -> imagebuilder.provider.v1.RemoteArtifact.MetadataEntry
	27, // 13: imagebuilder.provider.v1.ValidateConfigRequest.credentials:type_name -> imagebuilder.provider.v1.ValidateConfigRequest.CredentialsEntry
	28, // 14: imagebuilder.provider.v1.ValidateConfigRequest.extra:type_name -> imagebuilder.provider.v1.ValidateConfigRequest.ExtraEntry
	29, // 15: imagebuilder.provider.v1.UploadChunk.metadata:type_name -> imagebuilder.provider.v1.UploadChunk.MetadataEntry
	30, // 16: imagebuilder.provider.v1.RegisterRequest.tags:type_name -> imagebuilder.provider.v1.RegisterRequest.TagsEntry
	31, // 17: imagebuilder.provider.v1.ImageRef.tags:type_name -> imagebuilder.provider.v1.ImageRef.TagsEntry
	0,  // 18: imagebuilder.provider.v1.PlatformProvider.GetCapabilities:input_type -> imagebuilder.provider.v1.Empty
	14, // 19: imagebuilder.provider.v1.PlatformProvider.ValidateConfig:input_type -> imagebuilder.provider.v1.ValidateConfigRequest
	16, // 20: imagebuilder.provider.v1.PlatformProvider.UploadArtifact:input_type -> imagebuilder.provider.v1.UploadChunk
	18, // 21: imagebuilder.provider.v1.PlatformProvider.RegisterImage:input_type -> imagebuilder.provider.v1.RegisterRequest
	20, // 22: imagebuilder.provider.v1.PlatformProvider.DeleteArtifact:input_type -> imagebuilder.provider.v1.DeleteRequest
	0,  // 23: imagebuilder.provider.v1.PlatformProvider.HealthCheck:input_type -> imagebuilder.provider.v1.Empty
	2,  // 24: imagebuilder.provider.v1.PlatformProvider.ReconcileRemoteBuild:input_type -> imagebuilder.provider.v1.RemoteBuildRequest
	2,  // 25: imagebuilder.provider.v1.PlatformProvider.CleanupRemoteBuild:input_type -> imagebuilder.provider.v1.RemoteBuildRequest
	1,  // 26: imagebuilder.provider.v1.PlatformProvider.GetCapabilities:output_type -> imagebuilder.provider.v1.CapabilitiesResponse
	15, // 27: imagebuilder.provider.v1.PlatformProvider.ValidateConfig:output_type -> imagebuilder.provider.v1.ValidateConfigResponse
	17, // 28: imagebuilder.provider.v1.PlatformProvider.UploadArtifact:output_type -> imagebuilder.provider.v1.UploadProgress
	19, // 29: imagebuilder.provider.v1.PlatformProvider.RegisterImage:output_type -> imagebuilder.provider.v1.ImageRef
	21, // 30: imagebuilder.provider.v1.PlatformProvider.DeleteArtifact:output_type -> imagebuilder.provider.v1.DeleteResponse
	22, // 31: imagebuilder.provider.v1.PlatformProvider.HealthCheck:output_type -> imagebuilder.provider.v1.HealthResponse
	9,  // 32: imagebuilder.provider.v1.PlatformProvider.ReconcileRemoteBuild:output_type -> imagebuilder.provider.v1.RemoteBuildResponse
	13, // 33: imagebuilder.provider.v1.PlatformProvider.CleanupRemoteBuild:output_type -> imagebuilder.provider.v1.RemoteBuildCleanupResponse
	26, // [26:34] is the sub-list for method output_type
	18, // [18:26] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_provider_proto_init() }
func file_provider_proto_init() {
	if File_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_provider_proto_rawDesc), len(file_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_provider_proto_goTypes,
		DependencyIndexes: file_provider_proto_depIdxs,
		MessageInfos:      file_provider_proto_msgTypes,
	}.Build()
	File_provider_proto = out.File
	file_provider_proto_goTypes = nil
	file_provider_proto_depIdxs = nil
}
