apiVersion: v2
name: imagebuilder-azure-tomcat
description: ArgoCD-ready Azure Tomcat VMImage example for imagebuilder
type: application
version: 0.4.1
appVersion: "0.4.1"
home: https://github.com/anwendt/imagebuilder
sources:
  - https://github.com/anwendt/imagebuilder
keywords:
  - imagebuilder
  - azure
  - tomcat
  - argocd
