apiVersion: v2
name: imagebuilder
description: Kubernetes-native VM Image Builder operator
type: application
version: 0.4.1
appVersion: "v0.4.1"
home: https://github.com/anwendt/imagebuilder
sources:
  - https://github.com/anwendt/imagebuilder
keywords:
  - imagebuilder
  - vm
  - operator
  - qemu
maintainers:
  - name: Platform Engineering
