apiVersion: imagebuilder.io/v1alpha1
kind: ProviderConfig
metadata:
  name: otc-ubuntu24
  namespace: imagebuilder-system
  labels:
    app.kubernetes.io/name: imagebuilder-otc-ubuntu24
    app.kubernetes.io/part-of: imagebuilder
spec:
  provider: openstack
  endpoint: https://iam.eu-de.otc.t-systems.com/v3
  region: eu-de
  credentials:
    secretRef:
      name: otc-credentials
      key: credentials
  extra:
    # httpProxy: http://proxy.example.com:8080
    # httpsProxy: http://proxy.example.com:8443
    # noProxy: localhost,127.0.0.1,.svc,.cluster.local,169.254.169.254
    remote.flavorRef: s3.medium.1
    remote.networkID: 11111111-1111-1111-1111-111111111111
    remote.securityGroups: imagebuilder-build
    remote.keyName: imagebuilder-builder
    remote.sshUser: linux
    image.visibility: private
