apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: imagebuilder-operator
  namespace: imagebuilder-system
  labels:
    app.kubernetes.io/name: imagebuilder-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: imagebuilder-operator
  namespaceSelector:
    matchNames:
      - imagebuilder-system
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
