{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "imagebuilder.serviceAccountName" . }}
  namespace: {{ include "imagebuilder.namespace" . }}
  labels:
    {{- include "imagebuilder.labels" . | nindent 4 }}
{{- end }}
